/************************************************************************************************************************************
* @author Sriram (Perficient, Inc.)
* @date 02/03/2021
*
* @group Coverage Check
*
* @description Coverage check related constant variables are defined here
* 
**************************************************************************************************************************************/
public class CDdCoverageCheckConstants {

    public final static Integer DEFAULT_BATCH_SIZE = Integer.valueOf(System.Label.Coverage_Chk_Default_Batch_Size);
    public final static Integer LAST_MODIFIED_DAYS = Integer.valueOf(System.Label.Coverage_Chk_Last_Modified_Days);
       
}