/********************************************************************************************************************
* @author Sriram (Perficient, Inc.)
* @date 05/17/2021
*
* @group Fee Onboarding API
*
* @description  A enum to represent various Fee Onboarding API Types. 
*   Note: The string values are also defined as picklist in custom metadata Fee_Onboarding_CPQ_Program__mdt
* 
**************************************************************************************************************************************/
public enum CDdFeeOnboardingApiType {
    MX_PROGRAM_FEE,
    MX_STOREFRONT_MONTHLY_FEE,
    CX_STOREFRONT_FEE
}