/********************************************************************************************************************
* @author Sriram
* @date 04/18/2022
*
* @group Merchant Services
*
* @description Enum class for Merchant Order Batch
* 
**************************************************************************************************************************************/
public enum CDdMxOrderBatchEnum {
    GENERATE_MX_ORDER,
    PROCESS_MX_ORDER,
    SEND_MX_ORDER_RETURN_LABEL
 }