/********************************************************************************************************************
* @author Sriram (Perficient, Inc.)
* @date 06/26/2019
*
* @group Trigger Handler Test
*
* @description Test for trigger handler CDdTriggerHistoryTriggerHandler
*
**************************************************************************************************************************************/
@isTest
public class CDdTriggerHistoryTriggerHandlerTest {

}