public with sharing class PSContract {

  public Integer revision_number;
  public Boolean active;
  public String type;
  public String change_summary;
  public Integer site;
  public String request;
  public Integer account;
  public Integer contract;
  public String version;
  public Integer created_by;
  public Integer updated_by;
  public String title;
  public List<PSRequestField> fields;
  public String created_time;
  public String updated_time;
  public String id;

}